# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eligibility_criteria_parser',
                'doc_host': 'https://Mikołaj Morzy.github.io',
                'git_url': 'https://github.com/Mikołaj Morzy/eligibility_criteria_parser',
                'lib_path': 'eligibility_criteria_parser'},
  'syms': { 'eligibility_criteria_parser.core': { 'eligibility_criteria_parser.core.entity_coverage': ( 'core.html#entity_coverage',
                                                                                                        'eligibility_criteria_parser/core.py'),
                                                  'eligibility_criteria_parser.core.extract_entities': ( 'core.html#extract_entities',
                                                                                                         'eligibility_criteria_parser/core.py'),
                                                  'eligibility_criteria_parser.core.get_criteria_with_entities': ( 'core.html#get_criteria_with_entities',
                                                                                                                   'eligibility_criteria_parser/core.py'),
                                                  'eligibility_criteria_parser.core.jaccard_score': ( 'core.html#jaccard_score',
                                                                                                      'eligibility_criteria_parser/core.py'),
                                                  'eligibility_criteria_parser.core.load_eligibility_criteria': ( 'core.html#load_eligibility_criteria',
                                                                                                                  'eligibility_criteria_parser/core.py'),
                                                  'eligibility_criteria_parser.core.prompt_predict': ( 'core.html#prompt_predict',
                                                                                                       'eligibility_criteria_parser/core.py')}}}
