# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eligibility_criteria_parser',
                'doc_host': 'https://Mikołaj Morzy.github.io',
                'git_url': 'https://github.com/Mikołaj Morzy/eligibility_criteria_parser',
                'lib_path': 'eligibility_criteria_parser'},
  'syms': { 'eligibility_criteria_parser.core': { 'eligibility_criteria_parser.core.foo': ( 'core.html#foo',
                                                                                            'eligibility_criteria_parser/core.py')}}}
